### PR TITLE
Set up demo Percy integration

### PR DESCRIPTION
**Pull request by thibaudcolas**
Implements a prototype visual regression testing setup, with [Percy](https://percy.io/) from BrowserStack ([wagtail#8138](https://github.com/wagtail/wagtail/issues/8138)).

## What this is

This PR is the proposed implementation for how we integrate Percy with our UI component library in Storybook, and our integration tests with Puppeteer. For every PR to Wagtail, in CircleCI, Percy will:

- Take a screenshot of every variation of every UI component we have in Storybook, and compare it to a base screenshot.
- Take whole-page screenshots where we set it up to as part of our E2E tests.

## Percy compared to other visual regression testing tools

Percy is very advanced as far as visual regression testing tools go:

- The Percy client only captures specially-designed DOM snapshots which are sent off to Percy’s servers for actual rendering in different browsers, and diffing with base screenshots, stored by Percy.
- Their GitHub integration will report results via status checks. An "error" means there are screenshot differences to review. A "pass" means either there are no differences to review, or all reported differences have been approved. This can also all be configured to be non-blocking and auto-approve without any manual step if we wanted to.
- The projects dashboard is hosted as a SaaS where all build results are publicly visible and there’s a straightforward UI to view changes one after the other, accepting or rejecting them along the way.

## Examples

To illustrate this a bit better, here are three PRs:

### Plenty of changes causing diffs

PR: <https://github.com/thibaudcolas/wagtail-fork/pull/5>

This PR contains a lot of UI changes that would be very hard to do automated tests for with other means than screenshot diffing. Some are legitimate changes, some are intended as bugs. The changes in the Percy UI have been left as-is, none are approved or rejected.

### Everything red

PR: <https://github.com/thibaudcolas/wagtail-fork/pull/7>

This PR doesn’t make any UI changes, yet there are still screenshot differences reported – they’re all issues with our visual regression setup, with parts of the UI that naturally change from build to build and will need special treatment to support this type of testing (which will be done if we proceed with using Percy for Wagtail).

For this PR, I’ve requested changes for all diffs to illustrate what this would look like.

### Everything green

PR: <https://github.com/thibaudcolas/wagtail-fork/pull/6>

For this PR, there were also changes reported due to setup issues. I’ve approved all changes to show what this would look like.

## Next steps

According to [our plan](https://github.com/wagtail/wagtail/issues/8138), we will want:

- Scott and Naomi to review this setup – how Percy is configured, what the PR workflow looks like, in this wagtail-fork project that’s completely standalone.
- Other core team members and contributors to provide feedback as they see fit.
- Thibaud to iterate on the prototype accordingly.

If we’re all happy with this, we will then re-implement the same setup on `wagtail/wagtail`, with the appropriate fixes so there are as few false positives as possible.

### CODE REVIEW

**Comment by Scotchester** [comment]
Does the Storybook example comment get the current date and time when rendered? Might want to hard code that or we'll have lots of these false positives:

Percy diff showing changed time being flagged

**Comment by Scotchester** [comment]
> ### Everything red
> 
> PR: #7
> 
> This PR doesn’t make any UI changes, yet there are still screenshot differences reported – they’re all issues with our visual regression setup, with parts of the UI that naturally change from build to build and will need special treatment to support this type of testing (which will be done if we proceed with using Percy for Wagtail).
> 
> For this PR, I’ve requested changes for all diffs to illustrate what this would look like.

What do you think is going on with this one? A race to load the SVG icons in before the snapshot is taken?

It does also highlight that we should only run Percy if relevant code (py, html, css, js, etc.) has changed.

**Comment by Scotchester** [comment]
> ### Everything green
> 
> PR: #6
> 
> For this PR, I’ve approved all changes to show what this would look like. The changes reported are also due to visual regression testing setup issues which we will resolve if we go ahead with this.

To confirm: The Percy checks failed initially on this PR, but were updated to passing after you approved the false positives?

**Comment by Scotchester** [comment]
@thibaudcolas This looks fantastic to me! Shame about the Percy Puppeteer / Jest issue forcing you to reimplement that code, but hopefully that can get put back to an official release soon.

I don't know/remember what the payment situation is for Percy, but we'll definitely want to follow through with implementing https://github.com/wagtail/wagtail/pull/6790 so we're not wasting resources unnecessarily running Percy tests for PRs where they're not needed.

**Comment by lb-** [comment]
This is awesome.

Not sure if we should maybe run this as a nightly task for a while? Instead of on every PR, this way we can get feedback on the process and try to smooth out potential false negatives.

However, I am also all for adopting this and adjusting as we go, new contributors will likely ignore failing items but we want to avoid the issues (like with the current Python 3.10 pipeline) where failing items just get ignored by us core team.

It will also be important to ensure this is easy to run locally, not sure if that is covered, when making intentional changes it should be clear how to flag them in advance as 'known'.

**Comment by nmorduch** [comment]
This is very cool! I think we'll need some clarity on the workflow for reviewing the changes, and I want to note that after I requested changed I couldn't find a way to un-request them, just to approve. 

We have under 50 prs opened each month, and though some will be pushed to multiple times, I think we may only need to cut down the number of screenshots a little bit. 
- Can we set the storybook tests to run only when there are changes to that part of the code? (and the puppeteer tests to still go on all prs). 
- We also could run the storybook tests on stories that combine multiple components, rather than with a separate screenshot for each individual one. 
-  For the puppeteer tests, @jacobtoppm suggests that maybe we could not only run percy last, but also run a smaller set of the puppeteer tests first, and a larger set only if the first set passes (if there's a way to have tests automatically pass without review)

**Pull request merged**
